x-environment: &environment
  environment:
    # NODE_ENV: development
    BACKEND_PORT: 8080

x-fuseki: &base-fuseki
  build:
    context: ./fuseki
  volumes:
    - ./fuseki/staging:/staging
    # - fuseki_data:/jena-fuseki/databases
  user: root:root
  networks:
    - internal
  environment:
    - ADMIN_PASSWORD=admin
    - FUSEKI_DATASET_1=linkrec

x-backend: &base-backend
  networks:
    - internal
  ports:
    - 8080:8080

services:
  fuseki-dev:
    <<: *base-fuseki
    ports:
      - 3030:3030
  fuseki-prod:
    <<: *base-fuseki

  backend-dev:
    <<: [*base-backend, *environment]
    build:
      context: ./link-rec/apps/backend
      target: development
    volumes:
      - ./link-rec/apps/backend/src:/app/src
      - /app/node_modules

  backend-prod:
    <<: [*base-backend, *environment]
    build:
      context: ./link-rec/apps/backend
      target: production

  # frontend:
  #   build: ./link-rec/apps/frontend
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - backend
  #   networks:
  #     - internal-network
  #     - public-network

networks:
  internal:
    driver: bridge
  public: {}

volumes:
  fuseki_data:
