x-environment: &environment
  environment:
    # NODE_ENV: development
    BACKEND_PORT: 8080

x-fuseki: &base-fuseki
  image: stain/jena-fuseki
  volumes:
    - ./fuseki/fuseki-data:/fuseki
    - ./fuseki/staging:/staging
    # - fuseki-data:/fuseki/databases
    # - ./jena-fuseki/configuration:/fuseki/configuration
    # - ./jena-fuseki/shiro.ini:/fuseki/shiro.ini
    # - ./jena-fuseki/config.ttl:/fuseki/config.ttl
  user: root:root
  networks:
    - internal
  environment:
    - ADMIN_PASSWORD=admin
  command: ["./load.sh"]

x-backend: &base-backend
  networks:
    - internal
  ports:
    - 8080:8080

services:
  fuseki-dev:
    <<: *base-fuseki
    ports:
      - 3030:3030
  fuseki-prod:
    <<: *base-fuseki

  backend-dev:
    <<: [*base-backend, *environment]
    build:
      context: ./link-rec/apps/backend
      target: development
    volumes:
      - ./link-rec/apps/backend/src:/app/src
      - /app/node_modules

  backend-prod:
    <<: [*base-backend, *environment]
    build:
      context: ./link-rec/apps/backend
      target: production

  # frontend:
  #   build: ./link-rec/apps/frontend
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - backend
  #   networks:
  #     - internal-network
  #     - public-network

networks:
  internal:
    driver: bridge
  public: {}

volumes:
  fuseki-data:
