services:
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - database:/fuseki/databases
      - ./config:/fuseki/configuration
      - ./files:/fuseki/files

  # backend:
  #   build: ./link-rec/apps/backend
  #   depends_on:
  #     - fuseki
  #   networks:
  #     - internal-network

  # frontend:
  #   build: ./link-rec/apps/frontend
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - backend
  #   networks:
  #     - internal-network
  #     - public-network

networks:
  internal-network:
    internal: true
  public-network:

volumes:
  database:
